/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/brain-Circulation.glb");
  console.log(materials)
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Brain_With_Arteries"
          position={[0, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
          userData={{ name: "Brain_With_Arteries" }}
        >
          <group
            name="Arteries"
            position={[0, -46.8, 415.5]}
            rotation={[0, 0, Math.PI]}
            userData={{ name: "Arteries" }}
          >
            <mesh
              name="Anterior_Cerebral_Artery"
              castShadow
              receiveShadow
              geometry={nodes.Anterior_Cerebral_Artery.geometry}
              material={materials["Artery.001"]}
              position={[0, -18.9, 16.3]}
              rotation={[0, 0, -Math.PI]}
              userData={{ name: "Anterior_Cerebral_Artery" }}
            />
            <mesh
              name="Anterior_Communicating_Artery"
              castShadow
              receiveShadow
              geometry={nodes.Anterior_Communicating_Artery.geometry}
              material={materials["Artery.001"]}
              position={[0, -44.9, -68.4]}
              rotation={[0.2, 0, -Math.PI]}
              userData={{ name: "Anterior_Communicating_Artery" }}
            />
            <mesh
              name="Anterior_Inferior_Cerebellar_Artery"
              castShadow
              receiveShadow
              geometry={nodes.Anterior_Inferior_Cerebellar_Artery.geometry}
              material={materials["Artery.001"]}
              position={[0, -18.9, 16.3]}
              rotation={[0, 0, -Math.PI]}
              userData={{ name: "Anterior_Inferior_Cerebellar_Artery" }}
            />
            <mesh
              name="Basilar_Artery"
              castShadow
              receiveShadow
              geometry={nodes.Basilar_Artery.geometry}
              material={materials["Artery.001"]}
              position={[0, -64.9, -72.2]}
              rotation={[0.2, 0, -Math.PI]}
              userData={{ name: "Basilar_Artery" }}
            />
            <mesh
              name="Internal_Carotid_Artery"
              castShadow
              receiveShadow
              geometry={nodes.Internal_Carotid_Artery.geometry}
              material={materials["Artery.001"]}
              position={[0, -64.9, -72.2]}
              rotation={[0.2, 0, -Math.PI]}
              userData={{ name: "Internal_Carotid_Artery" }}
            />
            <mesh
              name="Middle_Cerebral_Artery"
              castShadow
              receiveShadow
              geometry={nodes.Middle_Cerebral_Artery.geometry}
              material={materials["Artery.001"]}
              position={[0, -18.9, 16.3]}
              rotation={[0, 0, -Math.PI]}
              userData={{ name: "Middle_Cerebral_Artery" }}
            />
            <mesh
              name="Posterior_Cerebral_Artery"
              castShadow
              receiveShadow
              geometry={nodes.Posterior_Cerebral_Artery.geometry}
              material={materials["Artery.001"]}
              position={[0, -18.9, 16.3]}
              rotation={[0, 0, -Math.PI]}
              userData={{ name: "Posterior_Cerebral_Artery" }}
            />
            <mesh
              name="Posterior_Communicating_Artery"
              castShadow
              receiveShadow
              geometry={nodes.Posterior_Communicating_Artery.geometry}
              material={materials["Artery.001"]}
              position={[0, -64.6, -75.5]}
              rotation={[0.2, 0, -Math.PI]}
              userData={{ name: "Posterior_Communicating_Artery" }}
            />
            <mesh
              name="Superior_Cerebellar_Artery"
              castShadow
              receiveShadow
              geometry={nodes.Superior_Cerebellar_Artery.geometry}
              material={materials["Artery.001"]}
              position={[0, -18.9, 16.3]}
              rotation={[0, 0, -Math.PI]}
              userData={{ name: "Superior_Cerebellar_Artery" }}
            />
            <mesh
              name="Vertebral_Artery"
              castShadow
              receiveShadow
              geometry={nodes.Vertebral_Artery.geometry}
              material={materials["Artery.001"]}
              position={[0, -64.9, -72.2]}
              rotation={[0.2, 0, -Math.PI]}
              userData={{ name: "Vertebral_Artery" }}
            />
          </group>
          <mesh
            name="Brain"
            castShadow
            receiveShadow
            geometry={nodes.Brain.geometry}
            material={materials["Brain Texture.001"]}
            position={[0, -18.2, -341.9]}
            rotation={[0, 0, -Math.PI]}
            userData={{ name: "Brain" }}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/brain-Circulation.glb");
